### ISSUE TITLE
Launch MxPlayer with subtitles

### ISSUE THREAD

**Issue by vovaklh** [b14cknc0d3/extern_video_player_launcher#1]
Is it possible to launch MxPlayer by intent including url or local path to subtitles?

**Comment by y3l1n4ung** [comment]
Yes, you can pass subtitle key, values as args  ` launchMxPlayer(String url, String? mime, Map<String, dynamic>? args)` .
You can check how to do it at [MX PLAYER API LINK]( https://mx.j2inter.com/api).
